export default [
    {
        id:1,
        img: "../img/swimmer.jpg",
        rating: 4.8,
        reviewCount: 6,
        country: "USA",
        title: "Life lessons with this swimmer dude, who's name I do not know.",
        price: 136,
        openSpots: 0,
    },
    {
        id:2,
        img: "../img/pool.jpg",
        rating: 4.3,
        reviewCount: 145,
        country: "UK",
        title: "Cooking with swimming pool water",
        price: 16,
        openSpots: 6,
    },
    {
        id:3,
        img: "../img/rhino.webp",
        rating: 5.0,
        reviewCount: 67,
        country: "Kongo",
        title: "Rhino patting",
        price: 59,
        openSpots: 6,
    },
    {
        id:4,
        img: "../img/tennis.jpg",
        rating: 4.2,
        reviewCount: 21,
        country: "Italy",
        title: "Learn how to play tennis like a pro",
        price: 89,
        openSpots: 6,
    },
]